name: Lint

on: 
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create virtual environment
        run: python3 -m venv venv

      - name: Install dependencies
        run: |
          ./venv/bin/pip install -r requirements.txt
          ./venv/bin/pip install pylint pytest

      - name: Run lint with pylint
        run: ./venv/bin/pylint  --ignore=venv .  --fail-under=9

      - name: Run tests with pytest
        run: ./venv/bin/python -m pytest tests/ --doctest-modules -q --disable-warnings
