name: Lint

on: 
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug – List root folders
        run: ls -la

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./Docker-API/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Create Virtual Environment
        run: python3 -m venv venv
        working-directory: ./Docker-API

      - name: Install Docker-API dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt  
          pip install pylint
        working-directory: ./Docker-API

      - name: Run lint with pylint
        run: |
          source venv/bin/activate
          pylint . --fail-under=9
        working-directory: ./Docker-API

      - name: Run tests with pytest
        run: |
          source venv/bin/activate
          pytest tests/ --doctest-modules -q --disable-warnings
        working-directory: ./Docker-API
